---
title: "linear_modeling.qmd"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(glmmTMB)
library(MASS)
library(groupdata2)
library(lme4)

```

```{r}
getwd()
```

```{r}
gid <- read.csv("modified_data/gid_tracts.csv")
head(gid)

```

```{r}
set.seed(42069)
gid_sub <- gid |>
  mutate(comm_plan_name = as.factor(comm_plan_name),
         category = as.factor(category),
         case_age_day_log = log(case_age_days + 1))
# partition by neighborhood (community plan name)
# ensures that all reports from a neighborhood stay entirely in train OR test
neigh_partition <- partition(gid_sub, p=0.2, id_col = 'comm_plan_name')

# fixing case origin levels for cv:
all_levels <- unique(gid_sub$case_origin)
gid_sub$case_origin <- factor(gid_sub$case_origin, levels = all_levels)

```

```{r}
test_set <- neigh_partition[[1]]
train_set <- neigh_partition[[2]]
```

```{r}
train_set <- groupdata2::fold(train_set, k=5, id_col = 'comm_plan_name')
train_set |>
  arrange(.folds)

test_set <- groupdata2::fold(test_set, k=5, id_col = 'comm_plan_name')
test_set |>
  arrange(.folds)
```

```{r}
train_set |>
  group_by(tractce) |>
  summarize(count=n())
```

```{r}
linmodel1 = lm('case_age_day_log ~ C(category) + pd_count',
               data = gid_sub)
summary(linmodel1)

# Extract residuals and fitted values
diagnostics1 <- data.frame(
  Fitted = predict(linmodel1),
  Residuals = residuals(linmodel1)
)

# Plot Residuals vs Fitted
ggplot(diagnostics1, aes(x = Fitted, y = Residuals)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values",
       subtitle = "case_age_day_log ~ C(category) + pd_count",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()
```

```{r}
#Linear model 2
linmodel2 = lm('case_age_day_log ~ C(category) + pd_count + C(council_district)',
               data = gid_sub)
summary(linmodel2)

# Extract residuals and fitted values
diagnostics2 <- data.frame(
  Fitted = predict(linmodel2),
  Residuals = residuals(linmodel2)
)

# Plot Residuals vs Fitted
ggplot(diagnostics2, aes(x = Fitted, y = Residuals)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values",
       subtitle = "case_age_day_log ~ C(category) + pd_count + C(council_district)",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()

#seeing if case_origin would work too
linmodel3 = lm('case_age_day_log ~ C(category) + pd_count + C(council_district) + C(case_origin)',
               data = gid_sub
               )
```

```{r}
#With random ints
linmodel4 = lmer('case_age_day_log ~ C(category) + pd_count + C(council_district) + (1|tractce)',
               data = gid_sub)

# Extract residuals and fitted values
diagnostics4 <- data.frame(
  Fitted = predict(linmodel4),
  Residuals = residuals(linmodel4)
)

# Plot Residuals vs Fitted
ggplot(diagnostics4, aes(x = Fitted, y = Residuals)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values",
       subtitle = "case_age_day_log ~ C(category) + pd_count + C(council_district) + (1|tractce)",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()


linmodel5 = lmer('case_age_day_log ~ C(category) + pd_count + (1|tractce)',
               data = gid_sub)
summary(linmodel5)

# Extract residuals and fitted values
diagnostics <- data.frame(
  Fitted = predict(linmodel5),
  Residuals = residuals(linmodel5)
)

# Plot Residuals vs Fitted
ggplot(diagnostics, aes(x = Fitted, y = Residuals)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values",
       subtitle = "case_age_day_log ~ C(category) + pd_count + (1|tractce)",
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()

```

```{r}
library(stargazer)

stargazer(linmodel1, linmodel2, linmodel5, linmodel4,
          font.size = "small",
          align = TRUE,
          column.sep.width = "-15pt",
          #omit.stat=c("f", "ser"),
          no.space = TRUE,
          title = "Regression Results")


#MULTICOLLINEARITY CHECK
library(performance)
check_collinearity(linmodel4)

```

```{r}
# MAE metric
mae_fn <- function(predicted, observed){
  mean(abs(observed - predicted))
}

mse_fcn <- function(predicted, observed){
  mean((observed - predicted)**2, na.rm = TRUE)
}

group_cv <- function(train_set, test_set, k=5, modelnum){
  results <- c()
  for (fold in 1:k){
    train_sub <- train_set[train_set$.folds != fold,]
    test_sub  <- test_set[test_set$.folds == fold,]
    
    #checking for new case_origin levels since this was throwing errors without this check
    trained_origins <- unique(train_sub$case_origin)
    trained_categories <- unique(train_sub$category)
    trained_councildist <- unique(train_sub$council_district)
    test_sub <- test_sub[test_sub$case_origin %in% trained_origins, ]
    test_sub <- test_sub[test_sub$category %in% trained_categories, ]
    test_sub <- test_sub[test_sub$council_district %in% trained_councildist, ]
    if (nrow(test_sub) == 0) {
      warning(paste("Fold", fold, "skipped: No valid test rows after filtering unseen levels."))
      next
    }
    
    if (modelnum == 1){
      model = lm('case_age_day_log ~ C(category) + pd_count',
               data = train_sub)
    } else if (modelnum == 2){
      model = lm('case_age_day_log ~ C(category) + pd_count + C(council_district)',
               data = train_sub)
    } else if (modelnum == 3){
      model = lm('case_age_day_log ~ C(category) + pd_count + C(council_district) + C(case_origin)',
               data = train_sub)
    } else if (modelnum == 4){
      model = lmer('case_age_day_log ~ C(category) + pd_count + C(case_origin) + (1|tractce)',
               data = train_sub)
    } else if (modelnum == 5){
      model = lmer('case_age_day_log ~ C(category) + pd_count + (1|tractce)',
               data = train_sub)
    } else {
      model = lmer('case_age_day_log ~ C(category) + pd_count + C(council_district) + (1|tractce)',
               data = train_sub)
    }
    
    predicted  <- predict(model, test_sub, allow.new.levels=TRUE)
    results[fold] <- mse_fcn(predicted, test_sub$case_age_day_log)
    #results[fold] <- mean((predicted - test_sub$"case_age_days_log")^2)
  }
  
  return(c('MSE' = mean(results)))
}
```

```{r}
start.time <- Sys.time()
cv_model1 <- group_cv(train_set, test_set, k=5, 1)
saveRDS(cv_model1, "linmodel1.rds")
cv_model2 <- group_cv(train_set, test_set, k=5, 2)
saveRDS(cv_model2, "linmodel2.rds")
# cv_model3 <- group_cv(train_set, test_set, k=5, 3)
# saveRDS(cv_model3, "linmodel3.rds")
#cv_model4 <- group_cv(train_set, test_set, k=5, 4)
cv_model5 <- group_cv(train_set, test_set, k=5, 5)
cv_model6 <- group_cv(train_set, test_set, k=5, 6)
saveRDS(cv_model5, "linmodel5.rds")

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken


```

```{r}
library(cv) #install.packages("cv")

cv_results <- cv(linmodel1, data = gid_sub, k = 5, seed = 123)
summary(cv_results)

```

```{r}
ggplot(gid_sub, aes(x = log(pd_count + 1), y = case_age_day_log)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  labs(title = "Case Age by PD Count and Category",
       x = "PD Count",
       y = "Log(Case Age Days + 1)") +
  theme_minimal()
```
```{r}

```